name: Deploy


on:
  workflow_dispatch:
  schedule:
    - cron: '27 3 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Step 2 - GitHub Action if statement (true)
      env: 
        WHO_TO_TRUST: ${{ secrets.SECRET_TOKEN }}
      if:  env.WHO_TO_TRUST == 'TrustNo1'
      run: echo "I know what the secret token is!"
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Use gcloud CLI
      run: gcloud info
    - name: Deploy using Google Cloud Run
      run: |-
        gcloud config set run/region us-central1
        gcloud config set project datasette-ripgrep-ets
        datasette publish cloudrun --metadata metadata.yml \
          --static all:all \
          --install=https://github.com/simonw/datasette-ripgrep/archive/main.zip \
          --apt-get-install ripgrep \
          --service datasette-ripgrep-ets
