name: Deploy


on:
  workflow_dispatch:
  schedule:
    - cron: '27 3 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt
    - name: Git clone ETS repos
      run: |-
        ./download_source.sh
    - name: Set up Cloud Run
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Configure Docker
      run: gcloud auth configure-docker --quiet  
    - name: Deploy using Google Cloud Run
      run: |-
        datasette publish cloudrun --metadata metadata.yml \
          --static all:all \
          --install=https://github.com/simonw/datasette-ripgrep/archive/main.zip \
          --apt-get-install ripgrep \
          --service datasette-ripgrep-ets
